/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model;


import com.example.demo.model.tables.Customers;
import com.example.demo.model.tables.Employees;
import com.example.demo.model.tables.Offices;
import com.example.demo.model.tables.Orderdetails;
import com.example.demo.model.tables.Orders;
import com.example.demo.model.tables.Payments;
import com.example.demo.model.tables.Productlines;
import com.example.demo.model.tables.Products;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in classicmodels
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>classicmodels.customers</code>.
     */
    public static final Customers CUSTOMERS = com.example.demo.model.tables.Customers.CUSTOMERS;

    /**
     * The table <code>classicmodels.employees</code>.
     */
    public static final Employees EMPLOYEES = com.example.demo.model.tables.Employees.EMPLOYEES;

    /**
     * The table <code>classicmodels.offices</code>.
     */
    public static final Offices OFFICES = com.example.demo.model.tables.Offices.OFFICES;

    /**
     * The table <code>classicmodels.orderdetails</code>.
     */
    public static final Orderdetails ORDERDETAILS = com.example.demo.model.tables.Orderdetails.ORDERDETAILS;

    /**
     * The table <code>classicmodels.orders</code>.
     */
    public static final Orders ORDERS = com.example.demo.model.tables.Orders.ORDERS;

    /**
     * The table <code>classicmodels.payments</code>.
     */
    public static final Payments PAYMENTS = com.example.demo.model.tables.Payments.PAYMENTS;

    /**
     * The table <code>classicmodels.productlines</code>.
     */
    public static final Productlines PRODUCTLINES = com.example.demo.model.tables.Productlines.PRODUCTLINES;

    /**
     * The table <code>classicmodels.products</code>.
     */
    public static final Products PRODUCTS = com.example.demo.model.tables.Products.PRODUCTS;
}
