/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers implements Serializable {

    private static final long serialVersionUID = 2133612949;

    private Integer    customernumber;
    private String     customername;
    private String     contactlastname;
    private String     contactfirstname;
    private String     phone;
    private String     addressline1;
    private String     addressline2;
    private String     city;
    private String     state;
    private String     postalcode;
    private String     country;
    private Integer    salesrepemployeenumber;
    private BigDecimal creditlimit;

    public Customers() {}

    public Customers(Customers value) {
        this.customernumber = value.customernumber;
        this.customername = value.customername;
        this.contactlastname = value.contactlastname;
        this.contactfirstname = value.contactfirstname;
        this.phone = value.phone;
        this.addressline1 = value.addressline1;
        this.addressline2 = value.addressline2;
        this.city = value.city;
        this.state = value.state;
        this.postalcode = value.postalcode;
        this.country = value.country;
        this.salesrepemployeenumber = value.salesrepemployeenumber;
        this.creditlimit = value.creditlimit;
    }

    public Customers(
        Integer    customernumber,
        String     customername,
        String     contactlastname,
        String     contactfirstname,
        String     phone,
        String     addressline1,
        String     addressline2,
        String     city,
        String     state,
        String     postalcode,
        String     country,
        Integer    salesrepemployeenumber,
        BigDecimal creditlimit
    ) {
        this.customernumber = customernumber;
        this.customername = customername;
        this.contactlastname = contactlastname;
        this.contactfirstname = contactfirstname;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.addressline2 = addressline2;
        this.city = city;
        this.state = state;
        this.postalcode = postalcode;
        this.country = country;
        this.salesrepemployeenumber = salesrepemployeenumber;
        this.creditlimit = creditlimit;
    }

    public Integer getCustomernumber() {
        return this.customernumber;
    }

    public void setCustomernumber(Integer customernumber) {
        this.customernumber = customernumber;
    }

    public String getCustomername() {
        return this.customername;
    }

    public void setCustomername(String customername) {
        this.customername = customername;
    }

    public String getContactlastname() {
        return this.contactlastname;
    }

    public void setContactlastname(String contactlastname) {
        this.contactlastname = contactlastname;
    }

    public String getContactfirstname() {
        return this.contactfirstname;
    }

    public void setContactfirstname(String contactfirstname) {
        this.contactfirstname = contactfirstname;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddressline1() {
        return this.addressline1;
    }

    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    public String getAddressline2() {
        return this.addressline2;
    }

    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getPostalcode() {
        return this.postalcode;
    }

    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Integer getSalesrepemployeenumber() {
        return this.salesrepemployeenumber;
    }

    public void setSalesrepemployeenumber(Integer salesrepemployeenumber) {
        this.salesrepemployeenumber = salesrepemployeenumber;
    }

    public BigDecimal getCreditlimit() {
        return this.creditlimit;
    }

    public void setCreditlimit(BigDecimal creditlimit) {
        this.creditlimit = creditlimit;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customers (");

        sb.append(customernumber);
        sb.append(", ").append(customername);
        sb.append(", ").append(contactlastname);
        sb.append(", ").append(contactfirstname);
        sb.append(", ").append(phone);
        sb.append(", ").append(addressline1);
        sb.append(", ").append(addressline2);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(postalcode);
        sb.append(", ").append(country);
        sb.append(", ").append(salesrepemployeenumber);
        sb.append(", ").append(creditlimit);

        sb.append(")");
        return sb.toString();
    }
}
