/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employees implements Serializable {

    private static final long serialVersionUID = -1171076943;

    private Integer employeenumber;
    private String  lastname;
    private String  firstname;
    private String  extension;
    private String  email;
    private String  officecode;
    private Integer reportsto;
    private String  jobtitle;

    public Employees() {}

    public Employees(Employees value) {
        this.employeenumber = value.employeenumber;
        this.lastname = value.lastname;
        this.firstname = value.firstname;
        this.extension = value.extension;
        this.email = value.email;
        this.officecode = value.officecode;
        this.reportsto = value.reportsto;
        this.jobtitle = value.jobtitle;
    }

    public Employees(
        Integer employeenumber,
        String  lastname,
        String  firstname,
        String  extension,
        String  email,
        String  officecode,
        Integer reportsto,
        String  jobtitle
    ) {
        this.employeenumber = employeenumber;
        this.lastname = lastname;
        this.firstname = firstname;
        this.extension = extension;
        this.email = email;
        this.officecode = officecode;
        this.reportsto = reportsto;
        this.jobtitle = jobtitle;
    }

    public Integer getEmployeenumber() {
        return this.employeenumber;
    }

    public void setEmployeenumber(Integer employeenumber) {
        this.employeenumber = employeenumber;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getOfficecode() {
        return this.officecode;
    }

    public void setOfficecode(String officecode) {
        this.officecode = officecode;
    }

    public Integer getReportsto() {
        return this.reportsto;
    }

    public void setReportsto(Integer reportsto) {
        this.reportsto = reportsto;
    }

    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(employeenumber);
        sb.append(", ").append(lastname);
        sb.append(", ").append(firstname);
        sb.append(", ").append(extension);
        sb.append(", ").append(email);
        sb.append(", ").append(officecode);
        sb.append(", ").append(reportsto);
        sb.append(", ").append(jobtitle);

        sb.append(")");
        return sb.toString();
    }
}
