/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 425913282;

    private Integer    ordernumber;
    private String     productcode;
    private Integer    quantityordered;
    private BigDecimal priceeach;
    private Short      orderlinenumber;

    public Orderdetails() {}

    public Orderdetails(Orderdetails value) {
        this.ordernumber = value.ordernumber;
        this.productcode = value.productcode;
        this.quantityordered = value.quantityordered;
        this.priceeach = value.priceeach;
        this.orderlinenumber = value.orderlinenumber;
    }

    public Orderdetails(
        Integer    ordernumber,
        String     productcode,
        Integer    quantityordered,
        BigDecimal priceeach,
        Short      orderlinenumber
    ) {
        this.ordernumber = ordernumber;
        this.productcode = productcode;
        this.quantityordered = quantityordered;
        this.priceeach = priceeach;
        this.orderlinenumber = orderlinenumber;
    }

    public Integer getOrdernumber() {
        return this.ordernumber;
    }

    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    public String getProductcode() {
        return this.productcode;
    }

    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    public Integer getQuantityordered() {
        return this.quantityordered;
    }

    public void setQuantityordered(Integer quantityordered) {
        this.quantityordered = quantityordered;
    }

    public BigDecimal getPriceeach() {
        return this.priceeach;
    }

    public void setPriceeach(BigDecimal priceeach) {
        this.priceeach = priceeach;
    }

    public Short getOrderlinenumber() {
        return this.orderlinenumber;
    }

    public void setOrderlinenumber(Short orderlinenumber) {
        this.orderlinenumber = orderlinenumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orderdetails (");

        sb.append(ordernumber);
        sb.append(", ").append(productcode);
        sb.append(", ").append(quantityordered);
        sb.append(", ").append(priceeach);
        sb.append(", ").append(orderlinenumber);

        sb.append(")");
        return sb.toString();
    }
}
