/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = -240024755;

    private Integer   ordernumber;
    private Timestamp orderdate;
    private Timestamp requireddate;
    private Timestamp shippeddate;
    private String    status;
    private String    comments;
    private Integer   customernumber;

    public Orders() {}

    public Orders(Orders value) {
        this.ordernumber = value.ordernumber;
        this.orderdate = value.orderdate;
        this.requireddate = value.requireddate;
        this.shippeddate = value.shippeddate;
        this.status = value.status;
        this.comments = value.comments;
        this.customernumber = value.customernumber;
    }

    public Orders(
        Integer   ordernumber,
        Timestamp orderdate,
        Timestamp requireddate,
        Timestamp shippeddate,
        String    status,
        String    comments,
        Integer   customernumber
    ) {
        this.ordernumber = ordernumber;
        this.orderdate = orderdate;
        this.requireddate = requireddate;
        this.shippeddate = shippeddate;
        this.status = status;
        this.comments = comments;
        this.customernumber = customernumber;
    }

    public Integer getOrdernumber() {
        return this.ordernumber;
    }

    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    public Timestamp getOrderdate() {
        return this.orderdate;
    }

    public void setOrderdate(Timestamp orderdate) {
        this.orderdate = orderdate;
    }

    public Timestamp getRequireddate() {
        return this.requireddate;
    }

    public void setRequireddate(Timestamp requireddate) {
        this.requireddate = requireddate;
    }

    public Timestamp getShippeddate() {
        return this.shippeddate;
    }

    public void setShippeddate(Timestamp shippeddate) {
        this.shippeddate = shippeddate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Integer getCustomernumber() {
        return this.customernumber;
    }

    public void setCustomernumber(Integer customernumber) {
        this.customernumber = customernumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(ordernumber);
        sb.append(", ").append(orderdate);
        sb.append(", ").append(requireddate);
        sb.append(", ").append(shippeddate);
        sb.append(", ").append(status);
        sb.append(", ").append(comments);
        sb.append(", ").append(customernumber);

        sb.append(")");
        return sb.toString();
    }
}
