/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payments implements Serializable {

    private static final long serialVersionUID = 809911892;

    private Integer    customernumber;
    private String     checknumber;
    private Timestamp  paymentdate;
    private BigDecimal amount;

    public Payments() {}

    public Payments(Payments value) {
        this.customernumber = value.customernumber;
        this.checknumber = value.checknumber;
        this.paymentdate = value.paymentdate;
        this.amount = value.amount;
    }

    public Payments(
        Integer    customernumber,
        String     checknumber,
        Timestamp  paymentdate,
        BigDecimal amount
    ) {
        this.customernumber = customernumber;
        this.checknumber = checknumber;
        this.paymentdate = paymentdate;
        this.amount = amount;
    }

    public Integer getCustomernumber() {
        return this.customernumber;
    }

    public void setCustomernumber(Integer customernumber) {
        this.customernumber = customernumber;
    }

    public String getChecknumber() {
        return this.checknumber;
    }

    public void setChecknumber(String checknumber) {
        this.checknumber = checknumber;
    }

    public Timestamp getPaymentdate() {
        return this.paymentdate;
    }

    public void setPaymentdate(Timestamp paymentdate) {
        this.paymentdate = paymentdate;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Payments (");

        sb.append(customernumber);
        sb.append(", ").append(checknumber);
        sb.append(", ").append(paymentdate);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
