/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Products implements Serializable {

    private static final long serialVersionUID = -1261345221;

    private String     productcode;
    private String     productname;
    private String     productline;
    private String     productscale;
    private String     productvendor;
    private String     productdescription;
    private Short      quantityinstock;
    private BigDecimal buyprice;
    private BigDecimal msrp;

    public Products() {}

    public Products(Products value) {
        this.productcode = value.productcode;
        this.productname = value.productname;
        this.productline = value.productline;
        this.productscale = value.productscale;
        this.productvendor = value.productvendor;
        this.productdescription = value.productdescription;
        this.quantityinstock = value.quantityinstock;
        this.buyprice = value.buyprice;
        this.msrp = value.msrp;
    }

    public Products(
        String     productcode,
        String     productname,
        String     productline,
        String     productscale,
        String     productvendor,
        String     productdescription,
        Short      quantityinstock,
        BigDecimal buyprice,
        BigDecimal msrp
    ) {
        this.productcode = productcode;
        this.productname = productname;
        this.productline = productline;
        this.productscale = productscale;
        this.productvendor = productvendor;
        this.productdescription = productdescription;
        this.quantityinstock = quantityinstock;
        this.buyprice = buyprice;
        this.msrp = msrp;
    }

    public String getProductcode() {
        return this.productcode;
    }

    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    public String getProductname() {
        return this.productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getProductline() {
        return this.productline;
    }

    public void setProductline(String productline) {
        this.productline = productline;
    }

    public String getProductscale() {
        return this.productscale;
    }

    public void setProductscale(String productscale) {
        this.productscale = productscale;
    }

    public String getProductvendor() {
        return this.productvendor;
    }

    public void setProductvendor(String productvendor) {
        this.productvendor = productvendor;
    }

    public String getProductdescription() {
        return this.productdescription;
    }

    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    public Short getQuantityinstock() {
        return this.quantityinstock;
    }

    public void setQuantityinstock(Short quantityinstock) {
        this.quantityinstock = quantityinstock;
    }

    public BigDecimal getBuyprice() {
        return this.buyprice;
    }

    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    public BigDecimal getMsrp() {
        return this.msrp;
    }

    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Products (");

        sb.append(productcode);
        sb.append(", ").append(productname);
        sb.append(", ").append(productline);
        sb.append(", ").append(productscale);
        sb.append(", ").append(productvendor);
        sb.append(", ").append(productdescription);
        sb.append(", ").append(quantityinstock);
        sb.append(", ").append(buyprice);
        sb.append(", ").append(msrp);

        sb.append(")");
        return sb.toString();
    }
}
