/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Productlines implements Serializable {

    private static final long serialVersionUID = 734487329;

    private String productline;
    private String textdescription;
    private String htmldescription;
    private byte[] image;

    public Productlines() {}

    public Productlines(Productlines value) {
        this.productline = value.productline;
        this.textdescription = value.textdescription;
        this.htmldescription = value.htmldescription;
        this.image = value.image;
    }

    public Productlines(
        String productline,
        String textdescription,
        String htmldescription,
        byte[] image
    ) {
        this.productline = productline;
        this.textdescription = textdescription;
        this.htmldescription = htmldescription;
        this.image = image;
    }

    public String getProductline() {
        return this.productline;
    }

    public void setProductline(String productline) {
        this.productline = productline;
    }

    public String getTextdescription() {
        return this.textdescription;
    }

    public void setTextdescription(String textdescription) {
        this.textdescription = textdescription;
    }

    public String getHtmldescription() {
        return this.htmldescription;
    }

    public void setHtmldescription(String htmldescription) {
        this.htmldescription = htmldescription;
    }

    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte... image) {
        this.image = image;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Productlines (");

        sb.append(productline);
        sb.append(", ").append(textdescription);
        sb.append(", ").append(htmldescription);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
