/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.pojos;


import com.example.demo.model.com.example.demo.tables.tables.interfaces.IEmployees;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employees implements IEmployees {

    private static final long serialVersionUID = 547055586;

    private final Integer employeenumber;
    private final String  lastname;
    private final String  firstname;
    private final String  extension;
    private final String  email;
    private final String  officecode;
    private final Integer reportsto;
    private final String  jobtitle;

    public Employees(Employees value) {
        this.employeenumber = value.employeenumber;
        this.lastname = value.lastname;
        this.firstname = value.firstname;
        this.extension = value.extension;
        this.email = value.email;
        this.officecode = value.officecode;
        this.reportsto = value.reportsto;
        this.jobtitle = value.jobtitle;
    }

    public Employees(
        Integer employeenumber,
        String  lastname,
        String  firstname,
        String  extension,
        String  email,
        String  officecode,
        Integer reportsto,
        String  jobtitle
    ) {
        this.employeenumber = employeenumber;
        this.lastname = lastname;
        this.firstname = firstname;
        this.extension = extension;
        this.email = email;
        this.officecode = officecode;
        this.reportsto = reportsto;
        this.jobtitle = jobtitle;
    }

    @Override
    public Integer getEmployeenumber() {
        return this.employeenumber;
    }

    @Override
    public String getLastname() {
        return this.lastname;
    }

    @Override
    public String getFirstname() {
        return this.firstname;
    }

    @Override
    public String getExtension() {
        return this.extension;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public String getOfficecode() {
        return this.officecode;
    }

    @Override
    public Integer getReportsto() {
        return this.reportsto;
    }

    @Override
    public String getJobtitle() {
        return this.jobtitle;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(employeenumber);
        sb.append(", ").append(lastname);
        sb.append(", ").append(firstname);
        sb.append(", ").append(extension);
        sb.append(", ").append(email);
        sb.append(", ").append(officecode);
        sb.append(", ").append(reportsto);
        sb.append(", ").append(jobtitle);

        sb.append(")");
        return sb.toString();
    }
}
