/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.pojos;


import com.example.demo.model.com.example.demo.tables.tables.interfaces.IOffices;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Offices implements IOffices {

    private static final long serialVersionUID = -1999172709;

    private final String officecode;
    private final String city;
    private final String phone;
    private final String addressline1;
    private final String addressline2;
    private final String state;
    private final String country;
    private final String postalcode;
    private final String territory;

    public Offices(Offices value) {
        this.officecode = value.officecode;
        this.city = value.city;
        this.phone = value.phone;
        this.addressline1 = value.addressline1;
        this.addressline2 = value.addressline2;
        this.state = value.state;
        this.country = value.country;
        this.postalcode = value.postalcode;
        this.territory = value.territory;
    }

    public Offices(
        String officecode,
        String city,
        String phone,
        String addressline1,
        String addressline2,
        String state,
        String country,
        String postalcode,
        String territory
    ) {
        this.officecode = officecode;
        this.city = city;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.addressline2 = addressline2;
        this.state = state;
        this.country = country;
        this.postalcode = postalcode;
        this.territory = territory;
    }

    @Override
    public String getOfficecode() {
        return this.officecode;
    }

    @Override
    public String getCity() {
        return this.city;
    }

    @Override
    public String getPhone() {
        return this.phone;
    }

    @Override
    public String getAddressline1() {
        return this.addressline1;
    }

    @Override
    public String getAddressline2() {
        return this.addressline2;
    }

    @Override
    public String getState() {
        return this.state;
    }

    @Override
    public String getCountry() {
        return this.country;
    }

    @Override
    public String getPostalcode() {
        return this.postalcode;
    }

    @Override
    public String getTerritory() {
        return this.territory;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Offices (");

        sb.append(officecode);
        sb.append(", ").append(city);
        sb.append(", ").append(phone);
        sb.append(", ").append(addressline1);
        sb.append(", ").append(addressline2);
        sb.append(", ").append(state);
        sb.append(", ").append(country);
        sb.append(", ").append(postalcode);
        sb.append(", ").append(territory);

        sb.append(")");
        return sb.toString();
    }
}
