/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.pojos;


import com.example.demo.model.com.example.demo.tables.tables.interfaces.IOrders;

import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements IOrders {

    private static final long serialVersionUID = 73046433;

    private final Integer       ordernumber;
    private final LocalDateTime orderdate;
    private final LocalDateTime requireddate;
    private final LocalDateTime shippeddate;
    private final String        status;
    private final String        comments;
    private final Integer       customernumber;

    public Orders(Orders value) {
        this.ordernumber = value.ordernumber;
        this.orderdate = value.orderdate;
        this.requireddate = value.requireddate;
        this.shippeddate = value.shippeddate;
        this.status = value.status;
        this.comments = value.comments;
        this.customernumber = value.customernumber;
    }

    public Orders(
        Integer       ordernumber,
        LocalDateTime orderdate,
        LocalDateTime requireddate,
        LocalDateTime shippeddate,
        String        status,
        String        comments,
        Integer       customernumber
    ) {
        this.ordernumber = ordernumber;
        this.orderdate = orderdate;
        this.requireddate = requireddate;
        this.shippeddate = shippeddate;
        this.status = status;
        this.comments = comments;
        this.customernumber = customernumber;
    }

    @Override
    public Integer getOrdernumber() {
        return this.ordernumber;
    }

    @Override
    public LocalDateTime getOrderdate() {
        return this.orderdate;
    }

    @Override
    public LocalDateTime getRequireddate() {
        return this.requireddate;
    }

    @Override
    public LocalDateTime getShippeddate() {
        return this.shippeddate;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public String getComments() {
        return this.comments;
    }

    @Override
    public Integer getCustomernumber() {
        return this.customernumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(ordernumber);
        sb.append(", ").append(orderdate);
        sb.append(", ").append(requireddate);
        sb.append(", ").append(shippeddate);
        sb.append(", ").append(status);
        sb.append(", ").append(comments);
        sb.append(", ").append(customernumber);

        sb.append(")");
        return sb.toString();
    }
}
