/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.pojos;


import com.example.demo.model.com.example.demo.tables.tables.interfaces.IPayments;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payments implements IPayments {

    private static final long serialVersionUID = 1553612966;

    private final Integer       customernumber;
    private final String        checknumber;
    private final LocalDateTime paymentdate;
    private final BigDecimal    amount;

    public Payments(Payments value) {
        this.customernumber = value.customernumber;
        this.checknumber = value.checknumber;
        this.paymentdate = value.paymentdate;
        this.amount = value.amount;
    }

    public Payments(
        Integer       customernumber,
        String        checknumber,
        LocalDateTime paymentdate,
        BigDecimal    amount
    ) {
        this.customernumber = customernumber;
        this.checknumber = checknumber;
        this.paymentdate = paymentdate;
        this.amount = amount;
    }

    @Override
    public Integer getCustomernumber() {
        return this.customernumber;
    }

    @Override
    public String getChecknumber() {
        return this.checknumber;
    }

    @Override
    public LocalDateTime getPaymentdate() {
        return this.paymentdate;
    }

    @Override
    public BigDecimal getAmount() {
        return this.amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Payments (");

        sb.append(customernumber);
        sb.append(", ").append(checknumber);
        sb.append(", ").append(paymentdate);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
