/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.pojos;


import com.example.demo.model.com.example.demo.tables.tables.interfaces.IProductlines;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Productlines implements IProductlines {

    private static final long serialVersionUID = -1203805320;

    private final String productline;
    private final String textdescription;
    private final String htmldescription;
    private final byte[] image;

    public Productlines(Productlines value) {
        this.productline = value.productline;
        this.textdescription = value.textdescription;
        this.htmldescription = value.htmldescription;
        this.image = value.image;
    }

    public Productlines(
        String productline,
        String textdescription,
        String htmldescription,
        byte[] image
    ) {
        this.productline = productline;
        this.textdescription = textdescription;
        this.htmldescription = htmldescription;
        this.image = image;
    }

    @Override
    public String getProductline() {
        return this.productline;
    }

    @Override
    public String getTextdescription() {
        return this.textdescription;
    }

    @Override
    public String getHtmldescription() {
        return this.htmldescription;
    }

    @Override
    public byte[] getImage() {
        return this.image;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Productlines (");

        sb.append(productline);
        sb.append(", ").append(textdescription);
        sb.append(", ").append(htmldescription);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
