/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICustomers extends Serializable {

    /**
     * Getter for <code>classicmodels.customers.customerNumber</code>.
     */
    public Integer getCustomernumber();

    /**
     * Getter for <code>classicmodels.customers.customerName</code>.
     */
    public String getCustomername();

    /**
     * Getter for <code>classicmodels.customers.contactLastName</code>.
     */
    public String getContactlastname();

    /**
     * Getter for <code>classicmodels.customers.contactFirstName</code>.
     */
    public String getContactfirstname();

    /**
     * Getter for <code>classicmodels.customers.phone</code>.
     */
    public String getPhone();

    /**
     * Getter for <code>classicmodels.customers.addressLine1</code>.
     */
    public String getAddressline1();

    /**
     * Getter for <code>classicmodels.customers.addressLine2</code>.
     */
    public String getAddressline2();

    /**
     * Getter for <code>classicmodels.customers.city</code>.
     */
    public String getCity();

    /**
     * Getter for <code>classicmodels.customers.state</code>.
     */
    public String getState();

    /**
     * Getter for <code>classicmodels.customers.postalCode</code>.
     */
    public String getPostalcode();

    /**
     * Getter for <code>classicmodels.customers.country</code>.
     */
    public String getCountry();

    /**
     * Getter for <code>classicmodels.customers.salesRepEmployeeNumber</code>.
     */
    public Integer getSalesrepemployeenumber();

    /**
     * Getter for <code>classicmodels.customers.creditLimit</code>.
     */
    public BigDecimal getCreditlimit();
}
