/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IEmployees extends Serializable {

    /**
     * Getter for <code>classicmodels.employees.employeeNumber</code>.
     */
    public Integer getEmployeenumber();

    /**
     * Getter for <code>classicmodels.employees.lastName</code>.
     */
    public String getLastname();

    /**
     * Getter for <code>classicmodels.employees.firstName</code>.
     */
    public String getFirstname();

    /**
     * Getter for <code>classicmodels.employees.extension</code>.
     */
    public String getExtension();

    /**
     * Getter for <code>classicmodels.employees.email</code>.
     */
    public String getEmail();

    /**
     * Getter for <code>classicmodels.employees.officeCode</code>.
     */
    public String getOfficecode();

    /**
     * Getter for <code>classicmodels.employees.reportsTo</code>.
     */
    public Integer getReportsto();

    /**
     * Getter for <code>classicmodels.employees.jobTitle</code>.
     */
    public String getJobtitle();
}
