/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IOffices extends Serializable {

    /**
     * Getter for <code>classicmodels.offices.officeCode</code>.
     */
    public String getOfficecode();

    /**
     * Getter for <code>classicmodels.offices.city</code>.
     */
    public String getCity();

    /**
     * Getter for <code>classicmodels.offices.phone</code>.
     */
    public String getPhone();

    /**
     * Getter for <code>classicmodels.offices.addressLine1</code>.
     */
    public String getAddressline1();

    /**
     * Getter for <code>classicmodels.offices.addressLine2</code>.
     */
    public String getAddressline2();

    /**
     * Getter for <code>classicmodels.offices.state</code>.
     */
    public String getState();

    /**
     * Getter for <code>classicmodels.offices.country</code>.
     */
    public String getCountry();

    /**
     * Getter for <code>classicmodels.offices.postalCode</code>.
     */
    public String getPostalcode();

    /**
     * Getter for <code>classicmodels.offices.territory</code>.
     */
    public String getTerritory();
}
