/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IOrders extends Serializable {

    /**
     * Getter for <code>classicmodels.orders.orderNumber</code>.
     */
    public Integer getOrdernumber();

    /**
     * Getter for <code>classicmodels.orders.orderDate</code>.
     */
    public LocalDateTime getOrderdate();

    /**
     * Getter for <code>classicmodels.orders.requiredDate</code>.
     */
    public LocalDateTime getRequireddate();

    /**
     * Getter for <code>classicmodels.orders.shippedDate</code>.
     */
    public LocalDateTime getShippeddate();

    /**
     * Getter for <code>classicmodels.orders.status</code>.
     */
    public String getStatus();

    /**
     * Getter for <code>classicmodels.orders.comments</code>.
     */
    public String getComments();

    /**
     * Getter for <code>classicmodels.orders.customerNumber</code>.
     */
    public Integer getCustomernumber();
}
