/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPayments extends Serializable {

    /**
     * Getter for <code>classicmodels.payments.customerNumber</code>.
     */
    public Integer getCustomernumber();

    /**
     * Getter for <code>classicmodels.payments.checkNumber</code>.
     */
    public String getChecknumber();

    /**
     * Getter for <code>classicmodels.payments.paymentDate</code>.
     */
    public LocalDateTime getPaymentdate();

    /**
     * Getter for <code>classicmodels.payments.amount</code>.
     */
    public BigDecimal getAmount();
}
