/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProductlines extends Serializable {

    /**
     * Getter for <code>classicmodels.productlines.productLine</code>.
     */
    public String getProductline();

    /**
     * Getter for <code>classicmodels.productlines.textDescription</code>.
     */
    public String getTextdescription();

    /**
     * Getter for <code>classicmodels.productlines.htmlDescription</code>.
     */
    public String getHtmldescription();

    /**
     * Getter for <code>classicmodels.productlines.image</code>.
     */
    public byte[] getImage();
}
