/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProducts extends Serializable {

    /**
     * Getter for <code>classicmodels.products.productCode</code>.
     */
    public String getProductcode();

    /**
     * Getter for <code>classicmodels.products.productName</code>.
     */
    public String getProductname();

    /**
     * Getter for <code>classicmodels.products.productLine</code>.
     */
    public String getProductline();

    /**
     * Getter for <code>classicmodels.products.productScale</code>.
     */
    public String getProductscale();

    /**
     * Getter for <code>classicmodels.products.productVendor</code>.
     */
    public String getProductvendor();

    /**
     * Getter for <code>classicmodels.products.productDescription</code>.
     */
    public String getProductdescription();

    /**
     * Getter for <code>classicmodels.products.quantityInStock</code>.
     */
    public Short getQuantityinstock();

    /**
     * Getter for <code>classicmodels.products.buyPrice</code>.
     */
    public BigDecimal getBuyprice();

    /**
     * Getter for <code>classicmodels.products.MSRP</code>.
     */
    public BigDecimal getMsrp();
}
