/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables;


import com.example.demo.model.com.example.demo.tables.Classicmodels;
import com.example.demo.model.com.example.demo.tables.Keys;
import com.example.demo.model.com.example.demo.tables.tables.records.PaymentsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DateAsTimestampBinding;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payments extends TableImpl<PaymentsRecord> {

    private static final long serialVersionUID = 2103794983;

    /**
     * The reference instance of <code>classicmodels.payments</code>
     */
    public static final Payments PAYMENTS = new Payments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentsRecord> getRecordType() {
        return PaymentsRecord.class;
    }

    /**
     * The column <code>classicmodels.payments.customerNumber</code>.
     */
    public final TableField<PaymentsRecord, Integer> CUSTOMERNUMBER = createField("customerNumber", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>classicmodels.payments.checkNumber</code>.
     */
    public final TableField<PaymentsRecord, String> CHECKNUMBER = createField("checkNumber", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.payments.paymentDate</code>.
     */
    public final TableField<PaymentsRecord, LocalDateTime> PAYMENTDATE = createField("paymentDate", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "", new DateAsTimestampBinding());

    /**
     * The column <code>classicmodels.payments.amount</code>.
     */
    public final TableField<PaymentsRecord, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2).nullable(false), this, "");

    /**
     * Create a <code>classicmodels.payments</code> table reference
     */
    public Payments() {
        this("payments", null);
    }

    /**
     * Create an aliased <code>classicmodels.payments</code> table reference
     */
    public Payments(String alias) {
        this(alias, PAYMENTS);
    }

    private Payments(String alias, Table<PaymentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Payments(String alias, Table<PaymentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Classicmodels.CLASSICMODELS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PaymentsRecord> getPrimaryKey() {
        return Keys.KEY_PAYMENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PaymentsRecord>> getKeys() {
        return Arrays.<UniqueKey<PaymentsRecord>>asList(Keys.KEY_PAYMENTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PaymentsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PaymentsRecord, ?>>asList(Keys.PAYMENTS_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Payments as(String alias) {
        return new Payments(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(String name) {
        return new Payments(name, null);
    }
}
