/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.daos;


import com.example.demo.model.com.example.demo.tables.tables.Customers;
import com.example.demo.model.com.example.demo.tables.tables.records.CustomersRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CustomersDao extends DAOImpl<CustomersRecord, com.example.demo.model.com.example.demo.tables.tables.pojos.Customers, Integer> {

    /**
     * Create a new CustomersDao without any configuration
     */
    public CustomersDao() {
        super(Customers.CUSTOMERS, com.example.demo.model.com.example.demo.tables.tables.pojos.Customers.class);
    }

    /**
     * Create a new CustomersDao with an attached configuration
     */
    @Autowired
    public CustomersDao(Configuration configuration) {
        super(Customers.CUSTOMERS, com.example.demo.model.com.example.demo.tables.tables.pojos.Customers.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.demo.model.com.example.demo.tables.tables.pojos.Customers object) {
        return object.getCustomernumber();
    }

    /**
     * Fetch records that have <code>customerNumber IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByCustomernumber(Integer... values) {
        return fetch(Customers.CUSTOMERS.CUSTOMERNUMBER, values);
    }

    /**
     * Fetch a unique record that has <code>customerNumber = value</code>
     */
    public com.example.demo.model.com.example.demo.tables.tables.pojos.Customers fetchOneByCustomernumber(Integer value) {
        return fetchOne(Customers.CUSTOMERS.CUSTOMERNUMBER, value);
    }

    /**
     * Fetch records that have <code>customerName IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByCustomername(String... values) {
        return fetch(Customers.CUSTOMERS.CUSTOMERNAME, values);
    }

    /**
     * Fetch records that have <code>contactLastName IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByContactlastname(String... values) {
        return fetch(Customers.CUSTOMERS.CONTACTLASTNAME, values);
    }

    /**
     * Fetch records that have <code>contactFirstName IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByContactfirstname(String... values) {
        return fetch(Customers.CUSTOMERS.CONTACTFIRSTNAME, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByPhone(String... values) {
        return fetch(Customers.CUSTOMERS.PHONE, values);
    }

    /**
     * Fetch records that have <code>addressLine1 IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByAddressline1(String... values) {
        return fetch(Customers.CUSTOMERS.ADDRESSLINE1, values);
    }

    /**
     * Fetch records that have <code>addressLine2 IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByAddressline2(String... values) {
        return fetch(Customers.CUSTOMERS.ADDRESSLINE2, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByCity(String... values) {
        return fetch(Customers.CUSTOMERS.CITY, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByState(String... values) {
        return fetch(Customers.CUSTOMERS.STATE, values);
    }

    /**
     * Fetch records that have <code>postalCode IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByPostalcode(String... values) {
        return fetch(Customers.CUSTOMERS.POSTALCODE, values);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByCountry(String... values) {
        return fetch(Customers.CUSTOMERS.COUNTRY, values);
    }

    /**
     * Fetch records that have <code>salesRepEmployeeNumber IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchBySalesrepemployeenumber(Integer... values) {
        return fetch(Customers.CUSTOMERS.SALESREPEMPLOYEENUMBER, values);
    }

    /**
     * Fetch records that have <code>creditLimit IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Customers> fetchByCreditlimit(BigDecimal... values) {
        return fetch(Customers.CUSTOMERS.CREDITLIMIT, values);
    }
}
