/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.daos;


import com.example.demo.model.com.example.demo.tables.tables.Orderdetails;
import com.example.demo.model.com.example.demo.tables.tables.records.OrderdetailsRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OrderdetailsDao extends DAOImpl<OrderdetailsRecord, com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails, Record2<Integer, String>> {

    /**
     * Create a new OrderdetailsDao without any configuration
     */
    public OrderdetailsDao() {
        super(Orderdetails.ORDERDETAILS, com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails.class);
    }

    /**
     * Create a new OrderdetailsDao with an attached configuration
     */
    @Autowired
    public OrderdetailsDao(Configuration configuration) {
        super(Orderdetails.ORDERDETAILS, com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, String> getId(com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails object) {
        return compositeKeyRecord(object.getOrdernumber(), object.getProductcode());
    }

    /**
     * Fetch records that have <code>orderNumber IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails> fetchByOrdernumber(Integer... values) {
        return fetch(Orderdetails.ORDERDETAILS.ORDERNUMBER, values);
    }

    /**
     * Fetch records that have <code>productCode IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails> fetchByProductcode(String... values) {
        return fetch(Orderdetails.ORDERDETAILS.PRODUCTCODE, values);
    }

    /**
     * Fetch records that have <code>quantityOrdered IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails> fetchByQuantityordered(Integer... values) {
        return fetch(Orderdetails.ORDERDETAILS.QUANTITYORDERED, values);
    }

    /**
     * Fetch records that have <code>priceEach IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails> fetchByPriceeach(BigDecimal... values) {
        return fetch(Orderdetails.ORDERDETAILS.PRICEEACH, values);
    }

    /**
     * Fetch records that have <code>orderLineNumber IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Orderdetails> fetchByOrderlinenumber(Short... values) {
        return fetch(Orderdetails.ORDERDETAILS.ORDERLINENUMBER, values);
    }
}
