/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.daos;


import com.example.demo.model.com.example.demo.tables.tables.Payments;
import com.example.demo.model.com.example.demo.tables.tables.records.PaymentsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PaymentsDao extends DAOImpl<PaymentsRecord, com.example.demo.model.com.example.demo.tables.tables.pojos.Payments, Record2<Integer, String>> {

    /**
     * Create a new PaymentsDao without any configuration
     */
    public PaymentsDao() {
        super(Payments.PAYMENTS, com.example.demo.model.com.example.demo.tables.tables.pojos.Payments.class);
    }

    /**
     * Create a new PaymentsDao with an attached configuration
     */
    @Autowired
    public PaymentsDao(Configuration configuration) {
        super(Payments.PAYMENTS, com.example.demo.model.com.example.demo.tables.tables.pojos.Payments.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, String> getId(com.example.demo.model.com.example.demo.tables.tables.pojos.Payments object) {
        return compositeKeyRecord(object.getCustomernumber(), object.getChecknumber());
    }

    /**
     * Fetch records that have <code>customerNumber IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Payments> fetchByCustomernumber(Integer... values) {
        return fetch(Payments.PAYMENTS.CUSTOMERNUMBER, values);
    }

    /**
     * Fetch records that have <code>checkNumber IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Payments> fetchByChecknumber(String... values) {
        return fetch(Payments.PAYMENTS.CHECKNUMBER, values);
    }

    /**
     * Fetch records that have <code>paymentDate IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Payments> fetchByPaymentdate(LocalDateTime... values) {
        return fetch(Payments.PAYMENTS.PAYMENTDATE, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Payments> fetchByAmount(BigDecimal... values) {
        return fetch(Payments.PAYMENTS.AMOUNT, values);
    }
}
