/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.daos;


import com.example.demo.model.com.example.demo.tables.tables.Productlines;
import com.example.demo.model.com.example.demo.tables.tables.records.ProductlinesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ProductlinesDao extends DAOImpl<ProductlinesRecord, com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines, String> {

    /**
     * Create a new ProductlinesDao without any configuration
     */
    public ProductlinesDao() {
        super(Productlines.PRODUCTLINES, com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines.class);
    }

    /**
     * Create a new ProductlinesDao with an attached configuration
     */
    @Autowired
    public ProductlinesDao(Configuration configuration) {
        super(Productlines.PRODUCTLINES, com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines object) {
        return object.getProductline();
    }

    /**
     * Fetch records that have <code>productLine IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines> fetchByProductline(String... values) {
        return fetch(Productlines.PRODUCTLINES.PRODUCTLINE, values);
    }

    /**
     * Fetch a unique record that has <code>productLine = value</code>
     */
    public com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines fetchOneByProductline(String value) {
        return fetchOne(Productlines.PRODUCTLINES.PRODUCTLINE, value);
    }

    /**
     * Fetch records that have <code>textDescription IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines> fetchByTextdescription(String... values) {
        return fetch(Productlines.PRODUCTLINES.TEXTDESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>htmlDescription IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines> fetchByHtmldescription(String... values) {
        return fetch(Productlines.PRODUCTLINES.HTMLDESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>image IN (values)</code>
     */
    public List<com.example.demo.model.com.example.demo.tables.tables.pojos.Productlines> fetchByImage(byte[]... values) {
        return fetch(Productlines.PRODUCTLINES.IMAGE, values);
    }
}
