/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables;


import com.example.demo.model.com.example.demo.tables.tables.Customers;
import com.example.demo.model.com.example.demo.tables.tables.Employees;
import com.example.demo.model.com.example.demo.tables.tables.Offices;
import com.example.demo.model.com.example.demo.tables.tables.Orderdetails;
import com.example.demo.model.com.example.demo.tables.tables.Orders;
import com.example.demo.model.com.example.demo.tables.tables.Payments;
import com.example.demo.model.com.example.demo.tables.tables.Productlines;
import com.example.demo.model.com.example.demo.tables.tables.Products;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classicmodels extends SchemaImpl {

    private static final long serialVersionUID = -1065919662;

    /**
     * The reference instance of <code>classicmodels</code>
     */
    public static final Classicmodels CLASSICMODELS = new Classicmodels();

    /**
     * The table <code>classicmodels.customers</code>.
     */
    public final Customers CUSTOMERS = com.example.demo.model.com.example.demo.tables.tables.Customers.CUSTOMERS;

    /**
     * The table <code>classicmodels.employees</code>.
     */
    public final Employees EMPLOYEES = com.example.demo.model.com.example.demo.tables.tables.Employees.EMPLOYEES;

    /**
     * The table <code>classicmodels.offices</code>.
     */
    public final Offices OFFICES = com.example.demo.model.com.example.demo.tables.tables.Offices.OFFICES;

    /**
     * The table <code>classicmodels.orderdetails</code>.
     */
    public final Orderdetails ORDERDETAILS = com.example.demo.model.com.example.demo.tables.tables.Orderdetails.ORDERDETAILS;

    /**
     * The table <code>classicmodels.orders</code>.
     */
    public final Orders ORDERS = com.example.demo.model.com.example.demo.tables.tables.Orders.ORDERS;

    /**
     * The table <code>classicmodels.payments</code>.
     */
    public final Payments PAYMENTS = com.example.demo.model.com.example.demo.tables.tables.Payments.PAYMENTS;

    /**
     * The table <code>classicmodels.productlines</code>.
     */
    public final Productlines PRODUCTLINES = com.example.demo.model.com.example.demo.tables.tables.Productlines.PRODUCTLINES;

    /**
     * The table <code>classicmodels.products</code>.
     */
    public final Products PRODUCTS = com.example.demo.model.com.example.demo.tables.tables.Products.PRODUCTS;

    /**
     * No further instances allowed
     */
    private Classicmodels() {
        super("classicmodels", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customers.CUSTOMERS,
            Employees.EMPLOYEES,
            Offices.OFFICES,
            Orderdetails.ORDERDETAILS,
            Orders.ORDERS,
            Payments.PAYMENTS,
            Productlines.PRODUCTLINES,
            Products.PRODUCTS);
    }
}
