/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables;


import com.example.demo.model.com.example.demo.tables.tables.Customers;
import com.example.demo.model.com.example.demo.tables.tables.Employees;
import com.example.demo.model.com.example.demo.tables.tables.Offices;
import com.example.demo.model.com.example.demo.tables.tables.Orderdetails;
import com.example.demo.model.com.example.demo.tables.tables.Orders;
import com.example.demo.model.com.example.demo.tables.tables.Payments;
import com.example.demo.model.com.example.demo.tables.tables.Productlines;
import com.example.demo.model.com.example.demo.tables.tables.Products;
import com.example.demo.model.com.example.demo.tables.tables.records.CustomersRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.EmployeesRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.OfficesRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.OrderdetailsRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.OrdersRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.PaymentsRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.ProductlinesRecord;
import com.example.demo.model.com.example.demo.tables.tables.records.ProductsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>classicmodels</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = UniqueKeys0.KEY_CUSTOMERS_PRIMARY;
    public static final UniqueKey<EmployeesRecord> KEY_EMPLOYEES_PRIMARY = UniqueKeys0.KEY_EMPLOYEES_PRIMARY;
    public static final UniqueKey<OfficesRecord> KEY_OFFICES_PRIMARY = UniqueKeys0.KEY_OFFICES_PRIMARY;
    public static final UniqueKey<OrderdetailsRecord> KEY_ORDERDETAILS_PRIMARY = UniqueKeys0.KEY_ORDERDETAILS_PRIMARY;
    public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = UniqueKeys0.KEY_ORDERS_PRIMARY;
    public static final UniqueKey<PaymentsRecord> KEY_PAYMENTS_PRIMARY = UniqueKeys0.KEY_PAYMENTS_PRIMARY;
    public static final UniqueKey<ProductlinesRecord> KEY_PRODUCTLINES_PRIMARY = UniqueKeys0.KEY_PRODUCTLINES_PRIMARY;
    public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = UniqueKeys0.KEY_PRODUCTS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomersRecord, EmployeesRecord> CUSTOMERS_IBFK_1 = ForeignKeys0.CUSTOMERS_IBFK_1;
    public static final ForeignKey<EmployeesRecord, OfficesRecord> EMPLOYEES_IBFK_2 = ForeignKeys0.EMPLOYEES_IBFK_2;
    public static final ForeignKey<EmployeesRecord, EmployeesRecord> EMPLOYEES_IBFK_1 = ForeignKeys0.EMPLOYEES_IBFK_1;
    public static final ForeignKey<OrderdetailsRecord, OrdersRecord> ORDERDETAILS_IBFK_1 = ForeignKeys0.ORDERDETAILS_IBFK_1;
    public static final ForeignKey<OrderdetailsRecord, ProductsRecord> ORDERDETAILS_IBFK_2 = ForeignKeys0.ORDERDETAILS_IBFK_2;
    public static final ForeignKey<OrdersRecord, CustomersRecord> ORDERS_IBFK_1 = ForeignKeys0.ORDERS_IBFK_1;
    public static final ForeignKey<PaymentsRecord, CustomersRecord> PAYMENTS_IBFK_1 = ForeignKeys0.PAYMENTS_IBFK_1;
    public static final ForeignKey<ProductsRecord, ProductlinesRecord> PRODUCTS_IBFK_1 = ForeignKeys0.PRODUCTS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = createUniqueKey(Customers.CUSTOMERS, "KEY_customers_PRIMARY", Customers.CUSTOMERS.CUSTOMERNUMBER);
        public static final UniqueKey<EmployeesRecord> KEY_EMPLOYEES_PRIMARY = createUniqueKey(Employees.EMPLOYEES, "KEY_employees_PRIMARY", Employees.EMPLOYEES.EMPLOYEENUMBER);
        public static final UniqueKey<OfficesRecord> KEY_OFFICES_PRIMARY = createUniqueKey(Offices.OFFICES, "KEY_offices_PRIMARY", Offices.OFFICES.OFFICECODE);
        public static final UniqueKey<OrderdetailsRecord> KEY_ORDERDETAILS_PRIMARY = createUniqueKey(Orderdetails.ORDERDETAILS, "KEY_orderdetails_PRIMARY", Orderdetails.ORDERDETAILS.ORDERNUMBER, Orderdetails.ORDERDETAILS.PRODUCTCODE);
        public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = createUniqueKey(Orders.ORDERS, "KEY_orders_PRIMARY", Orders.ORDERS.ORDERNUMBER);
        public static final UniqueKey<PaymentsRecord> KEY_PAYMENTS_PRIMARY = createUniqueKey(Payments.PAYMENTS, "KEY_payments_PRIMARY", Payments.PAYMENTS.CUSTOMERNUMBER, Payments.PAYMENTS.CHECKNUMBER);
        public static final UniqueKey<ProductlinesRecord> KEY_PRODUCTLINES_PRIMARY = createUniqueKey(Productlines.PRODUCTLINES, "KEY_productlines_PRIMARY", Productlines.PRODUCTLINES.PRODUCTLINE);
        public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = createUniqueKey(Products.PRODUCTS, "KEY_products_PRIMARY", Products.PRODUCTS.PRODUCTCODE);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CustomersRecord, EmployeesRecord> CUSTOMERS_IBFK_1 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_EMPLOYEES_PRIMARY, Customers.CUSTOMERS, "customers_ibfk_1", Customers.CUSTOMERS.SALESREPEMPLOYEENUMBER);
        public static final ForeignKey<EmployeesRecord, OfficesRecord> EMPLOYEES_IBFK_2 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_OFFICES_PRIMARY, Employees.EMPLOYEES, "employees_ibfk_2", Employees.EMPLOYEES.OFFICECODE);
        public static final ForeignKey<EmployeesRecord, EmployeesRecord> EMPLOYEES_IBFK_1 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_EMPLOYEES_PRIMARY, Employees.EMPLOYEES, "employees_ibfk_1", Employees.EMPLOYEES.REPORTSTO);
        public static final ForeignKey<OrderdetailsRecord, OrdersRecord> ORDERDETAILS_IBFK_1 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_ORDERS_PRIMARY, Orderdetails.ORDERDETAILS, "orderdetails_ibfk_1", Orderdetails.ORDERDETAILS.ORDERNUMBER);
        public static final ForeignKey<OrderdetailsRecord, ProductsRecord> ORDERDETAILS_IBFK_2 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_PRODUCTS_PRIMARY, Orderdetails.ORDERDETAILS, "orderdetails_ibfk_2", Orderdetails.ORDERDETAILS.PRODUCTCODE);
        public static final ForeignKey<OrdersRecord, CustomersRecord> ORDERS_IBFK_1 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_CUSTOMERS_PRIMARY, Orders.ORDERS, "orders_ibfk_1", Orders.ORDERS.CUSTOMERNUMBER);
        public static final ForeignKey<PaymentsRecord, CustomersRecord> PAYMENTS_IBFK_1 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_CUSTOMERS_PRIMARY, Payments.PAYMENTS, "payments_ibfk_1", Payments.PAYMENTS.CUSTOMERNUMBER);
        public static final ForeignKey<ProductsRecord, ProductlinesRecord> PRODUCTS_IBFK_1 = createForeignKey(com.example.demo.model.com.example.demo.tables.Keys.KEY_PRODUCTLINES_PRIMARY, Products.PRODUCTS, "products_ibfk_1", Products.PRODUCTS.PRODUCTLINE);
    }
}
