/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.records;


import com.example.demo.model.com.example.demo.tables.tables.Orders;
import com.example.demo.model.com.example.demo.tables.tables.interfaces.IOrders;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record7<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer>, IOrders {

    private static final long serialVersionUID = 351877470;

    /**
     * Setter for <code>classicmodels.orders.orderNumber</code>.
     */
    public void setOrdernumber(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>classicmodels.orders.orderNumber</code>.
     */
    @Override
    public Integer getOrdernumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>classicmodels.orders.orderDate</code>.
     */
    public void setOrderdate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>classicmodels.orders.orderDate</code>.
     */
    @Override
    public LocalDateTime getOrderdate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>classicmodels.orders.requiredDate</code>.
     */
    public void setRequireddate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>classicmodels.orders.requiredDate</code>.
     */
    @Override
    public LocalDateTime getRequireddate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>classicmodels.orders.shippedDate</code>.
     */
    public void setShippeddate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>classicmodels.orders.shippedDate</code>.
     */
    @Override
    public LocalDateTime getShippeddate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>classicmodels.orders.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>classicmodels.orders.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>classicmodels.orders.comments</code>.
     */
    public void setComments(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>classicmodels.orders.comments</code>.
     */
    @Override
    public String getComments() {
        return (String) get(5);
    }

    /**
     * Setter for <code>classicmodels.orders.customerNumber</code>.
     */
    public void setCustomernumber(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>classicmodels.orders.customerNumber</code>.
     */
    @Override
    public Integer getCustomernumber() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Orders.ORDERS.ORDERNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return Orders.ORDERS.ORDERDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return Orders.ORDERS.REQUIREDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return Orders.ORDERS.SHIPPEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Orders.ORDERS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Orders.ORDERS.COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Orders.ORDERS.CUSTOMERNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrdernumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getOrderdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getRequireddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getShippeddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCustomernumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value1(Integer value) {
        setOrdernumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value2(LocalDateTime value) {
        setOrderdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value3(LocalDateTime value) {
        setRequireddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value4(LocalDateTime value) {
        setShippeddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value6(String value) {
        setComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value7(Integer value) {
        setCustomernumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IOrders from) {
        setOrdernumber(from.getOrdernumber());
        setOrderdate(from.getOrderdate());
        setRequireddate(from.getRequireddate());
        setShippeddate(from.getShippeddate());
        setStatus(from.getStatus());
        setComments(from.getComments());
        setCustomernumber(from.getCustomernumber());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer ordernumber, LocalDateTime orderdate, LocalDateTime requireddate, LocalDateTime shippeddate, String status, String comments, Integer customernumber) {
        super(Orders.ORDERS);

        set(0, ordernumber);
        set(1, orderdate);
        set(2, requireddate);
        set(3, shippeddate);
        set(4, status);
        set(5, comments);
        set(6, customernumber);
    }
}
