/*
 * This file is generated by jOOQ.
*/
package com.example.demo.model.com.example.demo.tables.tables.records;


import com.example.demo.model.com.example.demo.tables.tables.Products;
import com.example.demo.model.com.example.demo.tables.tables.interfaces.IProducts;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record9<String, String, String, String, String, String, Short, BigDecimal, BigDecimal>, IProducts {

    private static final long serialVersionUID = 1323400365;

    /**
     * Setter for <code>classicmodels.products.productCode</code>.
     */
    public void setProductcode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>classicmodels.products.productCode</code>.
     */
    @Override
    public String getProductcode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>classicmodels.products.productName</code>.
     */
    public void setProductname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>classicmodels.products.productName</code>.
     */
    @Override
    public String getProductname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>classicmodels.products.productLine</code>.
     */
    public void setProductline(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>classicmodels.products.productLine</code>.
     */
    @Override
    public String getProductline() {
        return (String) get(2);
    }

    /**
     * Setter for <code>classicmodels.products.productScale</code>.
     */
    public void setProductscale(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>classicmodels.products.productScale</code>.
     */
    @Override
    public String getProductscale() {
        return (String) get(3);
    }

    /**
     * Setter for <code>classicmodels.products.productVendor</code>.
     */
    public void setProductvendor(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>classicmodels.products.productVendor</code>.
     */
    @Override
    public String getProductvendor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>classicmodels.products.productDescription</code>.
     */
    public void setProductdescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>classicmodels.products.productDescription</code>.
     */
    @Override
    public String getProductdescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>classicmodels.products.quantityInStock</code>.
     */
    public void setQuantityinstock(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>classicmodels.products.quantityInStock</code>.
     */
    @Override
    public Short getQuantityinstock() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>classicmodels.products.buyPrice</code>.
     */
    public void setBuyprice(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>classicmodels.products.buyPrice</code>.
     */
    @Override
    public BigDecimal getBuyprice() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>classicmodels.products.MSRP</code>.
     */
    public void setMsrp(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>classicmodels.products.MSRP</code>.
     */
    @Override
    public BigDecimal getMsrp() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, Short, BigDecimal, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, Short, BigDecimal, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Products.PRODUCTS.PRODUCTCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.PRODUCTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Products.PRODUCTS.PRODUCTLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Products.PRODUCTS.PRODUCTSCALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Products.PRODUCTS.PRODUCTVENDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Products.PRODUCTS.PRODUCTDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return Products.PRODUCTS.QUANTITYINSTOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return Products.PRODUCTS.BUYPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Products.PRODUCTS.MSRP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProductcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProductline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProductscale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProductvendor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProductdescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getQuantityinstock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getBuyprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getMsrp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value1(String value) {
        setProductcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value2(String value) {
        setProductname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value3(String value) {
        setProductline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value4(String value) {
        setProductscale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value5(String value) {
        setProductvendor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value6(String value) {
        setProductdescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value7(Short value) {
        setQuantityinstock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value8(BigDecimal value) {
        setBuyprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value9(BigDecimal value) {
        setMsrp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Short value7, BigDecimal value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IProducts from) {
        setProductcode(from.getProductcode());
        setProductname(from.getProductname());
        setProductline(from.getProductline());
        setProductscale(from.getProductscale());
        setProductvendor(from.getProductvendor());
        setProductdescription(from.getProductdescription());
        setQuantityinstock(from.getQuantityinstock());
        setBuyprice(from.getBuyprice());
        setMsrp(from.getMsrp());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(String productcode, String productname, String productline, String productscale, String productvendor, String productdescription, Short quantityinstock, BigDecimal buyprice, BigDecimal msrp) {
        super(Products.PRODUCTS);

        set(0, productcode);
        set(1, productname);
        set(2, productline);
        set(3, productscale);
        set(4, productvendor);
        set(5, productdescription);
        set(6, quantityinstock);
        set(7, buyprice);
        set(8, msrp);
    }
}
